### ISSUE TITLE
[MISC] Write down all possible transaction states in Magento and discuss the mappings to BP transaction states

### ISSUE THREAD

**Issue by gadimbaylisahil** [better-payment/bp-plugin-magento2-api2#11]
# Requirements

Write down all possible Magento transaction states and let's discuss their mappings to Better Payment transaction status here.

**Comment by hasanzade-hasan** [comment]
This is current (time of closing issue) status mapping: https://github.com/better-payment/bp-plugin-magento2-api2/blob/main/Util/PaymentStatusMapper.php
