### ISSUE TITLE
[Doc] Provide a changelog

### ISSUE THREAD

**Issue by gadimbaylisahil** [better-payment/bp-plugin-magento2-api2#12]
# Requirements

Provide a changelog based on https://keepachangelog.com/en/1.1.0/ specifications like in Shopware plugin. 

https://github.com/better-payment/bp-plugin-shopware6-api2/blob/main/CHANGELOG.md

**Comment by hasanzade-hasan** [comment]
Provided changelog: https://github.com/better-payment/bp-plugin-magento2-api2/blob/main/CHANGELOG.MD
